name: 'github-branch-name'
description: 'Get the branch name of both the source and new branch'
runs:
  using: "composite"
  steps:
    - name: Identifiy branch
      shell: bash
      run: |
        echo "/Repos/Vitesse/${{ github.ref }}"
        echo "/Repos/Vitesse/${{ github.ref_name }}"
        echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
