name: Retro
description: Create an retrospective
title: "[Retro]: "
labels: ["retro"]
projects: ["VitessePSP/6"]

body:
  - type: dropdown
    id: facilitator
    attributes:
      label: Faciliator
      description: Who is facilitating the retro?
      options:
        - Ben
        - Sam
        - Tim
    validations:
      required: true
- type: textarea
  id: prime-directive
  attributes:
    label: Prime Derective
    description: Define the Prime Directive
    value: |
      We will abide by the retrospective prime directive: 
      "Regardless of what we discover, we understand and truly believe tat everyone did the best job they could, given what they knew at the time, their skills and ability, the resources available, and the situation at hand"
