name: Retro
description: Create an retrospective
title: "[Retro]: "
labels: ["retro"]
projects: ["VitessePSP/6"]

body:
  - type: dropdown
    id: facilitator
    attributes:
      label: Faciliator
      description: Who is facilitating the retro?
      options:
        - Ben
        - Sam
        - Tim
    validations:
      required: true
