name: "Create Feature Branch"

on:
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.extract_branch.outputs.branch_name }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: identify branch
      id: extract_branch
      uses: ./.github/actions/github-branch-name
  update-repo:
    runs-on: ubuntu-latest
    needs: create-branch
    steps:
    - name: echo branch
      run: |
        echo "${{ needs.create-branch.outputs.branch-name }}"
      shell: bash
