name: "Create Feature Branch"

on:
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: identify branch
      id: extract_branch
      uses: ./.github/actions/github-branch-name
    - name: echo branch
      run: |
        echo "${{ steps.extract_branch.outputs.branch_name }}"
      shell: bash
