name: "Create Feature Branch"

on:
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Identifiy branch
      id: extract_branch
      run: |
        echo "/Repos/Vitesse/${{ github.ref }}"
        echo "/Repos/Vitesse/${{ github.ref_name }}"
        echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
    - name: echo branch
      run: |
        echo "{{ steps.extract_branch.outputs.branch }}"
