name: "Create Feature Branch"

on:
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
   # - name: Identifiy branch
   #   id: extract_branch2
   #   run: |
   #     echo "/Repos/Vitesse/${{ github.ref }}"
   #     echo "/Repos/Vitesse/${{ github.ref_name }}"
   #     echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
    - name: identify branch
      id: extract_branch
      uses: ./.github/actions/github-branch-name
    - name: echo branch
      run: |
        echo "${{ steps.extract_branch.outputs.branch }}"
      shell: bash
    - id: foo
      uses: ./.github/actions/hello-world
      with:
        who-to-greet: 'Mona the Octocat'
    - run: echo random-number ${{ steps.foo.outputs.random-number }}
      shell: bash
