name: "Create Feature Branch"

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'The name of the branch'
        required: true
jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Create feature branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin test-46
