name: "Create Feature Branch"

on:
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Identifiy branch
      run: |
        echo "/Repos/Vitesse/${{ github.ref }}"
        echo "${ github.ref_name}"
