name: "Databricks CICE"

on:
  create:

jobs:
  get-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Get branch name
        uses: ./.github/actions/github-branch-name
