name: "test branch name"

on:
  create:
jobs:
  branch-name:
   # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: branch_name
        #run: echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
        run: echo "branch=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT
      - name: Extract short branch name
        run: echo "${GITHUB_REF##*/}"
      - name: Use the value
        id: step_two
        run: |
          printf '%s\n' "$branch" # This will output 'yellow'
  #branch-report:
  #  runs-on: unbunto-latest
  #  steps:
  #    - name: output name
  #      run: echo "$GITHUB_OUTPUT.branch"
        

